### ISSUE TITLE
No new blocks are added without setting connect= or addnode= in conf

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#597] opened 2021-11-05 13:15 UTC
When I run with connect=x.x.x.x I find peers.
When I run with addnode=x.x.x.x I find peers
When I run without connect= / addnode= in btcsq.conf I don't find peers and getpeerinfo shows no result.

**Comment by Warchant** [comment] 2021-11-15 17:28
Duplicate of https://github.com/VeriBlock/vbk-ri-btc/issues/593

**Closed as completed by Warchant** 2021-11-15 17:28 UTC
Labels: daemon
